version: '3'
services:
  remo-exporter:
    ports:
      - 9352:9352
    image: kenfdev/remo-exporter:latest
    environment:
       OAUTH_TOKEN: ${REMO_OAUTH_TOKEN}
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    user: "${UID}:${GID}"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
    ports:
      - 9090:9090
    depends_on:
      - remo-exporter
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    user: "${UID}:${GID}"
    volumes:
      - ./data/grafana:/var/lib/grafana
    ports:
      - 3000:3000
    depends_on:
      - prometheus
  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - grafana
